title: Gayathri's webpage
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true
google_analytics: UA-210763081-1

theme: jekyll-theme-hacker